/*******************************************************************************
 * Copyright (c) 2013, 2016 Prepartic and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//   ["0000", "Test Completo", "tests/test_0000.html", ""],
var randomTestsSet = [
    $listaTestsGlobales:{
["$it.keyIdTestStr$", "$it.titulo$", "$it.htmlFilename$", ""],}$
];

//   ["0001", "Test del bloque A1 - 0001", "tests/test_0001.html", "A1", ""],
var blockTestsSet = [
    $listaTestsBloques:{
["$it.keyIdTestStr$", "$it.titulo$", "$it.htmlFilename$", "$it.idBloqueTematicaAnho$", ""],}$
];

//       ["0001", "Test del tema 1 - 0001", "tests/test_0001.html", "T1", ""],
var themeTestsSet = [
    $listaTestsTemas:{
["$it.keyIdTestStr$", "$it.titulo$", "$it.htmlFilename$", "$it.idBloqueTematicaAnho$", ""],}$
];

//    ["0001", "Test del 2013 - 0001", "tests/test_0001.html", "2013", ""],
var annosTestsSet = [
    $listaTestsAnnos:{
["$it.keyIdTestStr$", "$it.titulo$", "$it.htmlFilename$", "$it.idBloqueTematicaAnho$", ""],}$
];